// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-GWh_awhwy17Y8t2KzBmhIplRko67u40',
    appId: '1:286015491573:web:e44340f4bd4983dd49a4bc',
    messagingSenderId: '286015491573',
    projectId: 'app-vet-ae313',
    authDomain: 'app-vet-ae313.firebaseapp.com',
    databaseURL: 'https://app-vet-ae313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-vet-ae313.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4UQk3BWiG7vR-zxvIA1rU8JZGUvKmhU',
    appId: '1:286015491573:android:f5d77a3c10c10ce549a4bc',
    messagingSenderId: '286015491573',
    projectId: 'app-vet-ae313',
    databaseURL: 'https://app-vet-ae313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-vet-ae313.firebasestorage.app',
  );
}
